# Learn the Numpy concepts

In [1]:
#improt the numpy libraby
import numpy as np

In [3]:
#creating a array from the list
arr_id = np.array([1,2,3,4,5])
print("arr 1D:",arr_id)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("array 2d:",arr_2d)

arr 1D: [1 2 3 4 5]
array 2d: [[1 2 3]
 [4 5 6]]


List vs Numpy array

In [9]:
py_list = [1,2,3]
print("python list multiplication : ",py_list*2)

np_array = np.array([1,2,3]) #element by mutiplicatons.
print("numpy array multiplication: ",np_array*2)

#check time taken by list vs numpy array
import time 
start = time.time()
py_list = [i*2 for i in range(10000)]
print("\n List opertion time:",time.time() - start)

#numpy array
start = time.time()
np_array = np.arange(10000)*2
print("Numpy array Operstions time: ",time.time() - start)


python list multiplication :  [1, 2, 3, 1, 2, 3]
numpy array multiplication:  [2 4 6]

 List opertion time: 0.00087738037109375
Numpy array Operstions time:  0.0004897117614746094


Creating arrray from scratch

In [20]:
#make a array of zeros.
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

#make a array of ones.
ones = np.ones((4,4))
print("ones Array: \n",ones)

#make a array for a specific value.
full = np.full((2,3),7)
print("twos Array: \n",full)

#make a array with the random value.
random = np.random.random((3,5))
print("Random Array: \n",random)

#make a sequential array:
sequence = np.arange(0,12,2)
print("Sequence Array: ",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
twos Array: 
 [[7 7 7]
 [7 7 7]]
Random Array: 
 [[0.55508068 0.02727035 0.61350204 0.54819242 0.31692171]
 [0.36116978 0.61400561 0.95766614 0.75499361 0.06042471]
 [0.71602674 0.18986656 0.62427654 0.15807626 0.91813818]]
Sequence Array:  [ 0  2  4  6  8 10]


Vector , Matrix and Tensor

In [24]:
vector = np.array([1,2,3,4,5])
print("vector: ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: \n",tensor)

vector:  [1 2 3 4 5]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [26]:
arr = np.array([[1,2,3],[4,5,6]])
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("size[number of element inside the array] :",arr.size)
print("Data type: ",arr.dtype)

Shape:  (2, 3)
Dimension:  2
size[number of element inside the array] : 6
Data type:  int64


###Array reshapping

In [37]:
arr = np.arange(12)
print("original array:",arr)

#for convert the specific shape the array:
reshaped = arr.reshape((3,4))
print("\n reshapped Array: \n",reshaped)

#now convert into flattened.
flattened = reshaped.flatten()
print("\nFlattened Array \n",flattened)

# ravel ( return view, instead of copy)
ravel = reshaped.ravel()
print("\n ravel \n",ravel)

#transpose the array --- it convert the row num into column and column number into row
transpose = reshaped.T
print("\n Transpose Array: \n",transpose)


original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshapped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 ravel 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
