##Numpy Arrays Operations

In [1]:
import numpy as np

In [6]:
arr_2d = np.array([[1,3,4],[2,5,6],[7,8,9]])
print("specific element", arr_2d[2,2])
print("Enite specific row: ",arr_2d[1])
print("enite specific column: ",arr_2d[:,0])

specific element 9
Enite specific row:  [2 5 6]
enite specific column:  [1 2 7]


##Sorting

In [15]:
unsorted = np.array([2,1,3,2,21,3,23,5])
print("sorted array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[3,2]])
print("sorted 2d_array by column: \n",np.sort(arr_2d_unsorted, axis = 0))
print("\n sorted 2d_array by row: \n",np.sort(arr_2d_unsorted,axis=1))

sorted array:  [ 1  2  2  3  3  5 21 23]
sorted 2d_array by column: 
 [[1 1]
 [3 2]
 [3 2]]

 sorted 2d_array by row: 
 [[1 3]
 [1 2]
 [2 3]]


Filter

In [17]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = number[ number % 2 == 0]
print("even number:  ",even_number)

even number:   [ 2  4  6  8 10]


In [24]:
number

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Filter with mask

In [27]:
mask = number > 5
print("grater than 7 Numbers: ",number[mask])

grater than 7 Numbers:  [ 6  7  8  9 10]


Fancy indexing vs np.where()

In [30]:
indices = [0 , 2 ,5,7]
print(number[indices])

where_result = np.where(number > 5)
print("NP where ",number[where_result])

[1 3 6 8]
NP where  [ 6  7  8  9 10]


In [33]:
condition_array = np.where(number > 5, number * 4,number)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


Adding and removing data

In [35]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


Array compatibltity

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility Shape: ",a.shape == b.shape)

Compatibility Shape:  True


In [39]:
#adding the new row inside the original arrays
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))
print("original array: ",original)
print("add new row in original arrays: ",with_new_row)

#now add the new column in the original array.

new_column = np.array([[7],[8]])
with_new_column = np.hstack((original,new_column))
print("In the original array add new column: ",with_new_column)

original array:  [[1 2]
 [3 4]]
add new row in original arrays:  [[1 2]
 [3 4]
 [5 6]]
In the original array add new column:  [[1 2 7]
 [3 4 8]]


In [44]:
#delete 
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("After the deletion Arrays: ",deleted)

After the deletion Arrays:  [1 2 4 5]
